---
title: "Exploratory Data Analysis"
author: "crupley"
date: "Sunday, February 08, 2015"
output:
  html_document:
    number_sections: yes
    toc: yes
---

# Exploratory Data Analysis course notes

## Overview
---|---
**Dates** | 2014-09-04 : 2014-09-24
**Course** | Exploratory Data Analysis
**Portal** | Coursera
**Instructor(s)** | Jeff Leek, Brian Caffo, Roger Peng: Johns Hopkins
**Description** | This course covers the essential exploratory techniques for summarizing data. These techniques are typically applied before formal modeling commences and can help inform the development of more complex statistical models. Exploratory techniques are also important for eliminating or sharpening potential hypotheses about the world that can be addressed by the data. We will cover in detail the plotting systems in R as well as some of the basic principles of constructing data graphics. We will also cover some of the common multivariate statistical techniques used to visualize high-dimensional data.


## Course Notes

### Week 1
### Week 2
### Week 3
### Week 4


## Projects
