---
title: "Reproducible Research"
author: "crupley"
date: "Sunday, February 08, 2015"
output:
  html_document:
    number_sections: yes
    toc: yes
---

# Reproducible Research course notes

## Overview
---|---
**Dates** | 2014-09-05 : 2015-09-25
**Course** | Reproducible Research
**Portal** | Coursera
**Instructor(s)** | Jeff Leek, Brian Caffo, Roger Peng: Johns Hopkins
**Description** | This course focuses on the concepts and tools behind reporting modern data analyses in a reproducible manner. Reproducible research is the idea that data analyses, and more generally, scientific claims, are published with their data and software code so that others may verify the findings and build upon them.  The need for reproducibility is increasing dramatically as data analyses become more complex, involving larger datasets and more sophisticated computations. Reproducibility allows for people to focus on the actual content of a data analysis, rather than on superficial details reported in a written summary. In addition, reproducibility makes an analysis more useful to others because the data and code that actually conducted the analysis are available. This course will focus on literate statistical analysis tools which allow one to publish data analyses in a single document that allows others to easily execute the same analysis to obtain the same results.


## Course Notes

### Week 1
### Week 2
### Week 3
### Week 4


## Projects
