---
title: "Statistical Inference"
author: "crupley"
date: "Sunday, February 08, 2015"
output:
  html_document:
    number_sections: yes
    toc: yes
---

# Statistical Inference course notes

## Overview
---|---
**Dates** | 2014-10-06 : 2014-10-27
**Course** | Statistical Inference
**Portal** | Coursera
**Instructor(s)** | Jeff Leek, Brian Caffo, Roger Peng: Johns Hopkins
**Description** | Statistical inference is the process of drawing conclusions about populations or scientific truths from data. There are many modes of performing inference including statistical modeling, data oriented strategies and explicit use of designs and randomization in analyses. Furthermore, there are broad theories (frequentists, Bayesian, likelihood, design based, .) and numerous complexities (missing data, observed and unobserved confounding, biases) for performing inference. A practitioner can often be left in a debilitating maze of techniques, philosophies and nuance. This course presents the fundamentals of inference in a practical approach for getting things done. After taking this course, students will understand the broad directions of statistical inference and use this information for making informed choices in analyzing data.


## Course Notes

### Week 1
### Week 2
### Week 3
### Week 4


## Projects
