---
title: "Regression Models"
author: "crupley"
date: "Sunday, February 08, 2015"
output:
  html_document:
    number_sections: yes
    toc: yes
---

# Regression Models course notes

## Overview
---|---
**Dates** | 2014-10-07 : 2014-10-28
**Course** | Regression Models
**Portal** | Coursera
**Instructor(s)** | Jeff Leek, Brian Caffo, Roger Peng: Johns Hopkins
**Description** | Linear models, as their name implies, relates an outcome to a set of predictors of interest using linear assumptions.  Regression models, a subset of linear models, are the most important statistical analysis tool in a data scientist's toolkit. This course covers regression analysis, least squares and inference using regression models. Special cases of the regression model, ANOVA and ANCOVA will be covered as well. Analysis of residuals and variability will be investigated. The course will cover modern thinking on model selection and novel uses of regression models including scatterplot smoothing.


## Course Notes

### Week 1
### Week 2
### Week 3
### Week 4


## Projects
