---
title: "Practical Machine Learning"
author: "crupley"
date: "Sunday, February 08, 2015"
output:
  html_document:
    number_sections: yes
    toc: yes
---

# Practical Machine Learning course notes

## Overview
---|---
**Dates** | 2014-11-14 : 2015-01-12
**Course** | Practical Machine Learning
**Portal** | Coursera
**Instructor(s)** | Jeff Leek, Brian Caffo, Roger Peng: Johns Hopkins
**Description** | One of the most common tasks performed by data scientists and data analysts are prediction and machine learning. This course will cover the basic components of building and applying prediction functions with an emphasis on practical applications. The course will provide basic grounding in concepts such as training and tests sets, overfitting, and error rates. The course will also introduce a range of model based and algorithmic machine learning methods including regression, classification trees, Naive Bayes, and random forests. The course will cover the complete process of building prediction functions including data collection, feature creation, algorithms, and evaluation.


## Course Notes

### Week 1
### Week 2
### Week 3
### Week 4


## Projects
