---
title: "Machine Learning"
author: "crupley"
date: "Sunday, February 08, 2015"
output:
  html_document:
    number_sections: yes
    toc: yes
---

# Machine Learning

## Overview
---|---
**Dates** | 2014-09-29 :2014-12-15
**Course** | Machine Learning
**Portal** | Coursera
**Instructor(s)** | Andrew Ng: Stanford
**Description** | This course provides a broad introduction to machine learning, datamining, and statistical pattern recognition. Topics include: (i) Supervised learning (parametric/non-parametric algorithms, support vector machines, kernels, neural networks). (ii) Unsupervised learning (clustering, dimensionality reduction, recommender systems, deep learning). (iii) Best practices in machine learning (bias/variance theory; innovation process in machine learning and AI). The course will also draw from numerous case studies and applications, so that you'll also learn how to apply learning algorithms to building smart robots (perception, control), text understanding (web search, anti-spam), computer vision, medical informatics, audio, database mining, and other areas.


## Course Notes

### I. Introduction (Week 1)
### II. Linear Regression with One Variable (Week 1)
### III. Linear Algebra Review (Week 1, Optional)
### IV. Linear Regression with Multiple Variables (Week 2)
### V. Octave Tutorial (Week 2)
### VI. Logistic Regression (Week 3)
### VII. Regularization (Week 3)
### VIII. Neural Networks: Representation (Week 4)
### IX. Neural Networks: Learning (Week 5)
### X. Advice for Applying Machine Learning (Week 6)
### XI. Machine Learning System Design (Week 6)
### XII. Support Vector Machines (Week 7)
### XIII. Clustering (Week 8)
### XIV. Dimensionality Reduction (Week 8)
### XV. Anomaly Detection (Week 9)
### XVI. Recommender Systems (Week 9)
### XVII. Large Scale Machine Learning (Week 10)
### XVIII. Application Example: Photo OCR
### XIX. Conclusion


## Programming Exercises

### IV. Linear Regression with Multiple Variables (Week 2)
### VII. Regularization (Week 3)
### VIII. Neural Networks: Representation (Week 4)
### IX. Neural Networks: Learning (Week 5)
### X. Advice for Applying Machine Learning (Week 6)
### XII. Support Vector Machines (Week 7)
### XIV. Dimensionality Reduction (Week 8)


